name: Build and Publish Shared Library

on:
  push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11.1'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: python -m pip install --upgrade pip build twine

      - name: Install Julia dependencies
        run: |
          cd PowerModelsLibrary
          julia --project=. -e '
            using Pkg
            Pkg.instantiate()
            Pkg.add("PackageCompiler")
            Pkg.add("PowerModels")
            Pkg.add("JSON")
          '

      - name: Compile shared library
        run: |
          cd PowerModelsLibrary
          julia --project=. compile_library.jl

      - name: Copy shared library
        if: runner.os != 'Windows'
        run: |
            PLATFORM_DIR="src/PowerModelsBackend/shared_objects/libpowermodels/${{ matrix.os }}"
            mkdir -p $PLATFORM_DIR
            cp -r PowerModelsLibrary/libpowermodels/lib/julia $PLATFORM_DIR/
            cp PowerModelsLibrary/libpowermodels/lib/libpowermodels.* $PLATFORM_DIR/

      - name: Copy shared library
        if: runner.os == 'Windows'
        run: |
          $platformDir = "src\\PowerModelsBackend\\shared_objects\\libpowermodels\\${{ matrix.os }}"
          mkdir -Force -Path $platformDir 
          ls PowerModelsLibrary\libpowermodels
          Copy-Item -Path PowerModelsLibrary\libpowermodels\* -Destination $platformDir

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: src/PowerModelsBackend/shared_objects/libpowermodels/${{ matrix.os }}


      - name: Build PyPI package
        run: python -m build

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: src/PowerModelsBackend/shared_objects/libpowermodels/

      - name: Organize shared libraries for all platforms
        run: ls src/PowerModelsBackend/shared_objects/libpowermodels

      - name: Build PyPI package
        run: python -m build

      - name: Publish package
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_KEY }}
