name: Build and Publish Shared Library

on:
  push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: '1.11.1'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: python -m pip install --upgrade pip build twine

      - name: Install Julia dependencies
        run: |
          cd PowerModelsLibrary
          julia --project=. -e '
            using Pkg
            Pkg.instantiate()
            Pkg.add("PackageCompiler")
            Pkg.add("PowerModels")
            Pkg.add("JSON")
          '

      - name: Compile shared library
        run: |
          cd PowerModelsLibrary
          julia --project=. compile_library.jl

      - name: Copy shared library
        run: |
          mkdir -p src/PowerModelsBackend/shared_objects/libpowermodels
          cp -r PowerModelsLibrary/libpowermodels/lib/julia src/PowerModelsBackend/shared_objects/libpowermodels/
          cp PowerModelsLibrary/libpowermodels/lib/libpowermodels.* src/PowerModelsBackend/shared_objects/libpowermodels/

      - name: Build PyPI package
        run: python -m build

      - name: Publish package
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_KEY }}